apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapp
  namespace: myapp

namespace: myapp

resources:
  - helmrelease.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: homelab-foundations
  app.kubernetes.io/name: myapp
