apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: trino
  namespace: iceberg-system

namespace: iceberg-system

resources:
  - helmrelease.yaml
  - iceberg-rest-catalog.yaml
  - postgres-cluster.yaml
  - postgres-secret.yaml
  - services.yaml
  - ingress.yaml

# commonLabels removed to avoid conflicts with Helm-managed pod labels
