apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: trino
  namespace: iceberg-system

namespace: iceberg-system

resources:
  - helmrelease.yaml
  - iceberg-rest-catalog.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: homelab-foundations
  app.kubernetes.io/component: trino
