# Test PostgreSQL Cluster for CNPG Validation
# This is a temporary test cluster to verify CNPG functionality

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-test-postgres
  namespace: cnpg-test
  labels:
    app.kubernetes.io/name: cnpg-test-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cnpg-test
spec:
  instances: 1  # Single instance for homelab testing
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      # Performance tuning for homelab
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "256MB"
      work_mem: "2MB"
      maintenance_work_mem: "64MB"

      # Logging
      log_statement: "none"
      log_min_duration_statement: "1000"
      
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: testdb
      owner: testuser
      secret:
        name: cnpg-test-postgres-credentials
        
  # Storage configuration
  storage:
    size: 5Gi  # Small size for testing
    storageClass: longhorn
    
  # Resource allocation (minimal for testing)
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
      
  # Monitoring (enabled by default in CNPG)

  # Backup configuration
  backup:
    retentionPolicy: "7d"  # Short retention for testing
    barmanObjectStore:
      destinationPath: "s3://postgres-backups/cnpg-test"
      s3Credentials:
        accessKeyId:
          name: minio-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-credentials
          key: SECRET_ACCESS_KEY
      endpointURL: "http://minio-tenant-hl.minio-tenant.svc.cluster.local:9000"
