apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  releaseName: nats
  chart:
    spec:
      chart: nats
      version: "1.1.12"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  interval: 5m
  values:
    # NATS configuration
    config:
      # JetStream configuration
      jetstream:
        enabled: true
        fileStore:
          enabled: true
          dir: /data
          pvc:
            enabled: true
            size: 10Gi
            storageClassName: longhorn
        memoryStore:
          enabled: true
          maxSize: 1Gi

      # Monitor configuration for Prometheus
      monitor:
        enabled: true
        port: 8222

    # NATS container configuration
    container:
      image:
        tag: 2.10.11
      env:
        GOMEMLIMIT: 450MiB  # Set Go memory limit below container limit
      merge:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

    # Prometheus exporter
    promExporter:
      enabled: true
      port: 7777

    # Service configuration
    service:
      enabled: true
      merge:
        type: ClusterIP
      ports:
        nats:
          enabled: true
        monitor:
          enabled: true

    # StatefulSet configuration
    statefulSet:
      merge:
        spec:
          template:
            spec:
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
                fsGroupChangePolicy: "OnRootMismatch"
