apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  releaseName: nats
  chart:
    spec:
      chart: nats
      version: "1.1.12"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  interval: 5m
  values:
    # JetStream configuration
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: true
        size: 10Gi
        storageDirectory: /data
        storageClassName: longhorn  # Use Longhorn storage
    
    # NATS server configuration
    nats:
      image:
        tag: 2.10.11
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Prometheus metrics integration
    prometheus:
      enabled: true
    
    # Service configuration
    service:
      type: ClusterIP
      ports:
        client: 4222
        monitoring: 8222
    
    # Security context for homelab
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
