apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    name: longhorn-system
# MinIO namespaces managed by Helmfile
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-controller
  labels:
    name: haproxy-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: iceberg-system
  labels:
    name: iceberg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
  labels:
    name: nats
---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
  labels:
    name: clickhouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-system
  labels:
    name: temporal-system
