apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: homelab-clickhouse
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: homelab-cluster
        templates:
          podTemplate: pod-template
          volumeClaimTemplate: volume-template
        layout:
          shardsCount: 1
          replicasCount: 1
    
    settings:
      # Performance settings for homelab
      max_connections: 1024
      keep_alive_timeout: 3
      max_concurrent_queries: 100

      # Background processing optimization for idle state
      background_pool_size: 2                    # Reduce background threads (default: 16)
      background_merges_mutations_concurrency_ratio: 2  # Reduce merge concurrency
      max_bytes_to_merge_at_max_space_in_pool: 1073741824  # 1GB max merge size
      merge_tree/max_parts_in_total: 10000       # Reduce parts threshold
      merge_tree/parts_to_delay_insert: 150      # Delay inserts earlier
      merge_tree/parts_to_throw_insert: 300      # Throw errors earlier

      # Memory management
      max_memory_usage: 1610612736               # 1.5GB (75% of 2GB limit)
      max_memory_usage_for_user: 1610612736      # 1.5GB per user

      # Reduce background activity when idle
      background_schedule_pool_size: 2           # Reduce scheduler threads (default: 16)
      background_fetches_pool_size: 2            # Reduce fetch threads (default: 8)
      background_move_pool_size: 2               # Reduce move threads (default: 8)
      background_common_pool_size: 2             # Reduce common threads (default: 8)

      # Enable metrics for Prometheus
      prometheus/endpoint: "/metrics"
      prometheus/port: 9363
      prometheus/asynchronous_metrics: true
      prometheus/events: true
      prometheus/errors: true
      
    users:
      default/password: ""  # No password for homelab
      default/networks/ip: "::/0"  # Allow access from any IP for homelab
      default/profile: default
      default/quota: default
      
    profiles:
      default/max_memory_usage: 1610612736  # 1.5GB (increased to match settings)
      default/use_uncompressed_cache: 0
      default/load_balancing: random
      default/max_execution_time: 300       # 5 minutes max query time
      default/max_memory_usage_for_user: 1610612736  # 1.5GB per user
      
    quotas:
      default/interval/duration: 3600
      default/interval/queries: 0
      default/interval/errors: 0
      default/interval/result_rows: 0
      default/interval/read_rows: 0
      default/interval/execution_time: 0

  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 2
                  memory: 2Gi
              ports:
                - containerPort: 8123
                  name: http
                - containerPort: 9000
                  name: native
                - containerPort: 9363
                  name: metrics
              securityContext:
                runAsUser: 101
                runAsGroup: 101
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: volume-template
        spec:
          accessModes: 
            - ReadWriteOnce
          storageClassName: longhorn
          resources:
            requests:
              storage: 20Gi
