apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  # - clickhouse-installation.yaml  # Enable after operator is installed
  - services.yaml
  - ingress.yaml
  - servicemonitor.yaml
