apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgres
  namespace: postgres

namespace: postgres

resources:
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: homelab-foundations
  app.kubernetes.io/name: postgres
