apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: example-app
  namespace: example-app

namespace: example-app

resources:
  - postgres-cluster.yaml
  - postgres-secret.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: homelab-foundations
  app.kubernetes.io/name: example-app
