# Example PostgreSQL Credentials Secret
# IMPORTANT: This is an example only - never commit actual credentials to Git!
# Generate secure credentials and base64 encode them before use

apiVersion: v1
kind: Secret
metadata:
  name: example-app-postgres-credentials
  namespace: example-app
  labels:
    app.kubernetes.io/name: example-app-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: example-app
type: kubernetes.io/basic-auth
data:
  # Base64 encoded credentials - REPLACE WITH ACTUAL VALUES
  # To generate: echo -n "your-username" | base64
  username: ZXhhbXBsZV91c2Vy  # example_user (EXAMPLE ONLY)
  password: Y2hhbmdlbWUxMjM=    # changeme123 (EXAMPLE ONLY - USE SECURE PASSWORD)
  
  # Additional keys that applications might need
  postgres-username: ZXhhbXBsZV91c2Vy  # example_user (EXAMPLE ONLY)
  postgres-password: Y2hhbmdlbWUxMjM=    # changeme123 (EXAMPLE ONLY - USE SECURE PASSWORD)
