apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: '>=1.5.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    # Longhorn configuration values
    defaultSettings:
      defaultDataPath: /var/lib/longhorn/
      defaultDataLocality: best-effort
      replicaSoftAntiAffinity: false
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      upgradeChecker: false
      defaultReplicaCount: 1
      defaultLonghornStaticStorageClass: longhorn
      backupstorePollInterval: 300
      taintToleration: ""
      systemManagedComponentsNodeSelector: ""
      priorityClass: ""
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: true
      replicaZoneSoftAntiAffinity: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      allowNodeDrainWithLastHealthyReplica: false
      mkfsExt4Parameters: ""
      disableReplicaRebuild: false
      replicaReplenishmentWaitInterval: 600
      concurrentReplicaRebuildPerNodeLimit: 5
      disableRevisionCounter: true
      systemManagedPodsImagePullPolicy: if-not-present
      allowVolumeCreationWithDegradedAvailability: true
      autoCleanupSystemGeneratedSnapshot: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 0
      backingImageCleanupWaitInterval: 60
      backingImageRecoveryWaitInterval: 300
      guaranteedEngineManagerCPU: 12
      guaranteedReplicaManagerCPU: 12
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    service:
      ui:
        type: LoadBalancer
