apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: '1.20.0'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    # Pi-hole provider configuration
    provider:
      name: pihole

    # Pi-hole connection settings via environment variables
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: "http://pihole-web.dns-system.svc.cluster.local"
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        value: "homelab123"
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"

    # Manage homelab.local and runcell.local domains
    domainFilters:
      - homelab.local
      - runcell.local

    # Watch Ingress and Service resources
    sources:
      - ingress
      - service

    # Policy: sync will create and delete records
    policy: sync

    # Pi-hole doesn't support TXT records for registry, use noop
    registry: noop

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Log level for debugging
    logLevel: debug
