apiVersion: v1
kind: Service
metadata:
  name: simple-app
  namespace: simple-app
  labels:
    app.kubernetes.io/name: simple-app
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: simple-app
