apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cnpg
  namespace: cnpg-system

namespace: cnpg-system

resources:
  - namespace.yaml
  - helmrelease.yaml
  - monitoring.yaml
  - backup-config.yaml
