# PostgreSQL Credentials Secret Template
# Copy this template to your application directory and customize
#
# Usage:
# 1. Copy to clusters/um890/<app-name>/postgres-secret.yaml
# 2. Replace APP_NAME with actual application name
# 3. Replace APP_NAMESPACE with target namespace
# 4. Generate secure credentials (never commit actual credentials to Git)
#
# To generate secure credentials:
# echo -n "your-username" | base64
# echo -n "your-secure-password" | base64

apiVersion: v1
kind: Secret
metadata:
  name: APP_NAME-postgres-credentials
  namespace: APP_NAMESPACE
  labels:
    app.kubernetes.io/name: APP_NAME-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: APP_NAME
type: kubernetes.io/basic-auth
data:
  # Base64 encoded credentials
  # Replace with actual base64-encoded values
  username: REPLACE_WITH_BASE64_USERNAME
  password: REPLACE_WITH_BASE64_PASSWORD
  
  # Additional keys that applications might need
  # These should match the bootstrap configuration in postgres-cluster.yaml
  postgres-username: REPLACE_WITH_BASE64_USERNAME
  postgres-password: REPLACE_WITH_BASE64_PASSWORD
