# PostgreSQL Cluster Template for homelab-foundations
# Copy this template to your application directory and customize
#
# Usage:
# 1. Copy to clusters/um890/<app-name>/postgres-cluster.yaml
# 2. Replace all APP_* placeholders with actual values
# 3. Adjust resource allocation as needed
# 4. Customize backup path if required
#
# Example replacements:
# - APP_NAME: temporal
# - APP_NAMESPACE: temporal-system  
# - APP_DATABASE: temporal
# - APP_USER: temporal

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: APP_NAME-postgres
  namespace: APP_NAMESPACE
  labels:
    app.kubernetes.io/name: APP_NAME-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: APP_NAME
spec:
  instances: 1  # Single instance for homelab
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      # Performance tuning for homelab
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "256MB"
      work_mem: "2MB"
      maintenance_work_mem: "64MB"

      # Logging
      log_statement: "none"
      log_min_duration_statement: "1000"
      
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: APP_DATABASE
      owner: APP_USER
      secret:
        name: APP_NAME-postgres-credentials
        
  # Storage configuration
  storage:
    size: 20Gi
    storageClass: longhorn
    
  # Resource allocation (adjust per application)
  resources:
    requests:
      memory: 500Mi
      cpu: 250m
    limits:
      memory: 500Mi
      cpu: 500m
      
  # Monitoring (enabled by default in CNPG)

  # Backup configuration
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://postgres-backups/APP_NAME"
      s3Credentials:
        accessKeyId:
          name: minio-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-credentials
          key: SECRET_ACCESS_KEY
      endpointURL: "http://minio-tenant-hl.minio-tenant.svc.cluster.local:9000"
