apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal-system
spec:
  interval: 10m
  chart:
    spec:
      chart: temporal
      version: ">=0.64.0"
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: flux-system
  values:
    # Minimal resource allocation for homelab
    server:
      replicaCount: 1

      # Resource configuration for all services
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      
      # Database configuration
      config:
        persistence:
          default:
            driver: "sql"
            sql:
              driver: "postgres12"
              host: "temporal-postgres-rw.temporal-system.svc.cluster.local"
              port: 5432
              database: "temporal"
              user: "temporal"
              existingSecret: "temporal-postgres-credentials"
              secretKey: "password"
              maxConns: 20
              maxConnLifetime: "1h"
          visibility:
            driver: "sql"
            sql:
              driver: "postgres12"
              host: "temporal-postgres-rw.temporal-system.svc.cluster.local"
              port: 5432
              database: "temporal_visibility"
              user: "temporal"
              existingSecret: "temporal-postgres-credentials"
              secretKey: "password"
              maxConns: 10
              maxConnLifetime: "1h"

    # Web UI configuration
    web:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi
    
    # Disable bundled services (use existing infrastructure)
    cassandra:
      enabled: false

    mysql:
      enabled: false

    postgresql:
      enabled: false  # Using CNPG PostgreSQL

    elasticsearch:
      enabled: false  # Use existing monitoring stack if needed

    prometheus:
      enabled: false  # Use existing monitoring stack

    grafana:
      enabled: false  # Use existing monitoring stack
