apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-cluster.yaml
  - postgres-podmonitor.yaml
  # Secrets managed manually (not in Git for security)
  # - postgres-secret.yaml
  # - minio-backup-secret.yaml
  - helmrelease.yaml
  - services.yaml
  - ingress.yaml
  - servicemonitor.yaml
