# PodMonitor for Temporal PostgreSQL metrics
# Enables Prometheus to scrape PostgreSQL metrics directly from pods

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: temporal-postgres-metrics
  namespace: temporal-system
  labels:
    app.kubernetes.io/name: temporal-postgres
    app.kubernetes.io/component: database
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: temporal-postgres
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - temporal-system
