apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend-lb
  namespace: temporal-system
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
    app.kubernetes.io/service: loadbalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.0.250"
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
      protocol: TCP
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-web-lb
  namespace: temporal-system
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: web
    app.kubernetes.io/service: loadbalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.0.250"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: web
