apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: haproxy-controller
spec:
  interval: 10m
  chart:
    spec:
      chart: kubernetes-ingress
      version: "1.33.5"
      sourceRef:
        kind: HelmRepository
        name: haproxy-tech
        namespace: flux-system
  values:
    controller:
      name: haproxy-ingress
      ingressClass: haproxy
      service:
        type: LoadBalancer
        # loadBalancerIP: 10.0.0.245  # Configure for your MetalLB range
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    defaultBackend:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
