apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitored-app
  namespace: monitored-app

namespace: monitored-app

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: homelab-foundations
  app.kubernetes.io/name: monitored-app

replicas:
  - name: monitored-app
    count: 2
