apiVersion: v1
kind: Service
metadata:
  name: monitored-app
  namespace: monitored-app
  labels:
    app.kubernetes.io/name: monitored-app
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9100
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: monitored-app
